# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smClOGEfA7B9A5Q52ATvPVkLLDLHEUhV
"""

from google.colab.patches import cv2_imshow
import cv2

# Rasmlarni o'qish
file_names = ['rasm.png', 'picture.jpg', 'rasm1.jpg', 'surat.jpg', 'rasmlar.jpg']
images = []

for file_name in file_names:
    img = cv2.imread(file_name)
    if img is None:
        print(f"Fayl topilmadi: {file_name}")
    else:
        images.append(img)

# Rasmlarni ko'rsatish
for i, img in enumerate(images):
    print(f"Rasm {i+1}:")
    cv2_imshow(img)

# Rasmlarni kulrang formatga o'tkazish va ko'rsatish
for i, img in enumerate(images):
    if img is not None:
        gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        print(f"Rasm {i+1} (kulrang):")
        cv2_imshow(gray_img)